#include <string>
#include "skill_type.h"

const bool skills::SKILL_HAS_SPECIALTIES[] = {
    [ADMIN] = false,
    [ADVOCATE] = false,
    [ANIMALS] = true,
    [ATHLETICS] = true,
    [ART] = true,
    [ASTROGATION] = false,
    [BATTLE_DRESS] = false,
    [BROKER] = false,
    [CAROUSE] = false,
    [COMMS] = false,
    [COMPUTERS] = false,
    [DECEPTION] = false,
    [DIPLOMAT] = false,
    [DRIVE] = true,
    [ENGINEER] = true,
    [EXPLOSIVES] = false,
    [FLYER] = true,
    [GAMBLER] = false,
    [GUNNER] = true,
    [GUN_COMBAT] = true,
    [HEAVY_WEAPONS] = true,
    [INVESTIGATE] = false,
    [JACK_OF_ALL_TRADES] = false,
    [LANGUAGE] = true,
    [LEADERSHIP] = false,
    [MECHANIC] = false,
    [MEDIC] = false,
    [MELEE] = true,
    [NAVIGATION] = false,
    [PERSUADE] = false,
    [PILOT] = true,
    [RECON] = false,
    [REMOTE_OPERATIONS] = false,
    [SCIENCE_PHYSICAL] = true,
    [SCIENCE_LIFE] = true,
    [SCIENCE_SOCIAL] = true,
    [SCIENCE_SPACE] = true,
    [SEAFARER] = true,
    [SENSORS] = false,
    [STEALTH] = false,
    [STEWARD] = false,
    [STREETWISE] = false,
    [SURVIVAL] = false,
    [TACTICS] = true,
    [TRADE] = true,
    [VACC_SUIT] = false,
    [ZERO_G] = false
};

const std::string skills::SK_STRINGS[NUM_SKILLS_OVERALL] = {
    "Admin",
    "Advocate",
    "Animals",
    "Athletics",
    "Art",
    "Astrogation",
    "Battle Dress",
    "Broker",
    "Carouse",
    "Comms",
    "Computers",
    "Deception",
    "Diplomat",
    "Drive",
    "Engineer",
    "Explosives",
    "Flyer",
    "Gambler",
    "Gunner",
    "Gun Combat",
    "Heavy Weapons",
    "Investigate",
    "Jack of All Trades",
    "Language",
    "Leadership",
    "Mechanic",
    "Medic",
    "Melee",
    "Navigation",
    "Persuade",
    "Pilot",
    "Recon",
    "Remote Operations",
    "Physical Science",
    "Life Science",
    "Social Science",
    "Space Science",
    "Seafarer",
    "Sensors",
    "Stealth",
    "Steward",
    "Streetwise",
    "Survival",
    "Tactics",
    "Trade",
    "Vacc Suit",
    "Zero-G"
};
